Upgrade to react-map-gl 7, using deckgl as a control (#1800)
- with react-map-gl 7, we are forced to choose between
  * Root Deck, Map as child. Deckgl handles all camera and user input like before
    The major downside is that react-map-gl 7 dropped support for using their
    controls (NavigationControl, the '+/-/compass' at the top right
  * Root Map, deck as child. React-map-gl handles all camera and user input.
    some advanced deckgl features are not available, and it changes what we
    were doing.
- right click on a feature is not exposed in "MapRoot/DeckglChild"
  mode for now, implement it manually as per https://github.com/visgl/deck.gl/issues/8326
- remove project_size_at_latitude copy, it seems accessible now? Removing it
  fixes the following error and the arrows are still correctly displayed:
      luma.gl: GLSL compilation errors in vertex shader arrow-layer-vertex-shader-1
      658:  * Just to call it from project_size_all_zoom_levels().
      659:  */
      660: float project_size_at_latitude(float lat) {
      ^^^ ERROR: 'project_size_at_latitude' : function already has a body
      deck: initialization of ArrowLayer({id: 'lineLayer-ArrowNominalVoltage400'}):
        GLSL compilation errors in vertex shader arrow-layer-vertex-shader-1
- upgrade to latest mapboxgl v3, compatible with v2.
  mapboxglv3 adds the "mapbox standard style" (3D with trees and shadows), we are not using it yet
- Adding zIndex:0 on the map because deckgl had it, and the rest of our code used this fact
- I didn't add additional user gestures restrictions (like boxZoom false), we can choose what
we want. I kept the doubleClickZoom=false because it was explicitly set but we could remove it